version: '3.8'

services:
  ai-summary:
    build: .
    image: eastwind996/ai-summary-api:latest
    container_name: ai-summary-api
    env_file:
      - .env
    # environment:
      # 可以将注释去掉,直接设置密钥
      # - SecretId=123456
      # - SecretKey=123456
    ports:
      - "6123:1234"
    working_dir: /app
    restart: unless-stopped